package com.wx.server.dao;

import com.wx.server.entity.TbAptitude;
import com.wx.server.entity.TbAptitudeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAptitudeMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */
  int deleteByExample(TbAptitudeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */
  int insert(TbAptitude record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */
  int insertSelective(TbAptitude record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */List<TbAptitude> selectByExample(TbAptitudeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */
  TbAptitude selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbAptitude record,@Param("example") TbAptitudeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */int updateByExample(@Param("record") TbAptitude record,@Param("example") TbAptitudeExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbAptitude record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_aptitude
   * @mbg.generated
   */
  int updateByPrimaryKey(TbAptitude record);
}