package com.wx.server.dao;

import com.wx.server.entity.TbAppointment;
import com.wx.server.entity.TbAppointmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAppointmentMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */
  long countByExample(TbAppointmentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */
  int deleteByExample(TbAppointmentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */
  int insert(TbAppointment record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */
  int insertSelective(TbAppointment record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */List<TbAppointment> selectByExample(TbAppointmentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */
  TbAppointment selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbAppointment record,@Param("example") TbAppointmentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */int updateByExample(@Param("record") TbAppointment record,@Param("example") TbAppointmentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbAppointment record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_appointment
   * @mbg.generated
   */
  int updateByPrimaryKey(TbAppointment record);
}