package com.wx.server.dao;

import com.wx.server.entity.TbButton;
import com.wx.server.entity.TbButtonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbButtonMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */
  int deleteByExample(TbButtonExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */
  int insert(TbButton record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */
  int insertSelective(TbButton record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */List<TbButton> selectByExample(TbButtonExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */
  TbButton selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbButton record,@Param("example") TbButtonExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */int updateByExample(@Param("record") TbButton record,@Param("example") TbButtonExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbButton record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_button
   * @mbg.generated
   */
  int updateByPrimaryKey(TbButton record);
}