package com.wx.server.dao;

import com.wx.server.entity.TbCart;
import com.wx.server.entity.TbCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCartMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */
  long countByExample(TbCartExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */
  int deleteByExample(TbCartExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */
  int insert(TbCart record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */
  int insertSelective(TbCart record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */List<TbCart> selectByExample(TbCartExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */
  TbCart selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbCart record,@Param("example") TbCartExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */int updateByExample(@Param("record") TbCart record,@Param("example") TbCartExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbCart record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_cart
   * @mbg.generated
   */
  int updateByPrimaryKey(TbCart record);
}