package com.wx.server.dao;

import com.wx.server.entity.TbConfig;
import com.wx.server.entity.TbConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbConfigMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int deleteByExample(TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int insert(TbConfig record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int insertSelective(TbConfig record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */List<TbConfig> selectByExample(TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  TbConfig selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbConfig record,@Param("example") TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */int updateByExample(@Param("record") TbConfig record,@Param("example") TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbConfig record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int updateByPrimaryKey(TbConfig record);
}