package com.wx.server.dao;

import com.wx.server.entity.TbFile;
import com.wx.server.entity.TbFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    int deleteByExample(TbFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    int insert(TbFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    int insertSelective(TbFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    List<TbFile> selectByExample(TbFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    TbFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFile record, @Param("example") TbFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFile record, @Param("example") TbFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFile record);
}