package com.wx.server.dao;

import com.wx.server.entity.TbFreight;
import com.wx.server.entity.TbFreightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFreightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    int deleteByExample(TbFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    int insert(TbFreight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    int insertSelective(TbFreight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    List<TbFreight> selectByExample(TbFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    TbFreight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFreight record, @Param("example") TbFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFreight record, @Param("example") TbFreightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFreight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_freight
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFreight record);
}