package com.wx.server.dao;

import com.wx.server.entity.TbGoods;
import com.wx.server.entity.TbGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbGoodsMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  long countByExample(TbGoodsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  int deleteByExample(TbGoodsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  int insert(TbGoods record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  int insertSelective(TbGoods record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */List<TbGoods> selectByExampleWithBLOBs(TbGoodsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */List<TbGoods> selectByExample(TbGoodsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  TbGoods selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbGoods record,@Param("example") TbGoodsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */int updateByExampleWithBLOBs(@Param("record") TbGoods record,@Param("example") TbGoodsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */int updateByExample(@Param("record") TbGoods record,@Param("example") TbGoodsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbGoods record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  int updateByPrimaryKeyWithBLOBs(TbGoods record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_goods
   * @mbg.generated
   */
  int updateByPrimaryKey(TbGoods record);
}