package com.wx.server.dao;

import com.wx.server.entity.TbIdentification;
import com.wx.server.entity.TbIdentificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbIdentificationMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */
  int deleteByExample(TbIdentificationExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */
  int insert(TbIdentification record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */
  int insertSelective(TbIdentification record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */List<TbIdentification> selectByExample(TbIdentificationExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */
  TbIdentification selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbIdentification record,@Param("example") TbIdentificationExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */int updateByExample(@Param("record") TbIdentification record,@Param("example") TbIdentificationExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbIdentification record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_identification
   * @mbg.generated
   */
  int updateByPrimaryKey(TbIdentification record);
}