package com.wx.server.dao;

import com.wx.server.entity.TbMessage;
import com.wx.server.entity.TbMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    int deleteByExample(TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    int insert(TbMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    int insertSelective(TbMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    List<TbMessage> selectByExample(TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    TbMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbMessage record, @Param("example") TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbMessage record, @Param("example") TbMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbMessage record);
}