package com.wx.server.dao;

import com.wx.server.entity.TbOrder;
import com.wx.server.entity.TbOrderExample;
import com.wx.server.entity.TbOrderWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbOrderMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  long countByExample(TbOrderExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  int deleteByExample(TbOrderExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  int insert(TbOrderWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  int insertSelective(TbOrderWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */List<TbOrderWithBLOBs> selectByExampleWithBLOBs(TbOrderExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */List<TbOrder> selectByExample(TbOrderExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  TbOrderWithBLOBs selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbOrderWithBLOBs record,@Param("example") TbOrderExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */int updateByExampleWithBLOBs(@Param("record") TbOrderWithBLOBs record,@Param("example") TbOrderExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */int updateByExample(@Param("record") TbOrder record,@Param("example") TbOrderExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbOrderWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  int updateByPrimaryKeyWithBLOBs(TbOrderWithBLOBs record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_order
   * @mbg.generated
   */
  int updateByPrimaryKey(TbOrder record);
}