package com.wx.server.dao;

import com.wx.server.entity.TbRepairShop;
import com.wx.server.entity.TbRepairShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbRepairShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    long countByExample(TbRepairShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    int deleteByExample(TbRepairShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    int insert(TbRepairShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    int insertSelective(TbRepairShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    List<TbRepairShop> selectByExample(TbRepairShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    TbRepairShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbRepairShop record, @Param("example") TbRepairShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbRepairShop record, @Param("example") TbRepairShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbRepairShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_repair_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbRepairShop record);
}