package com.wx.server.dao;

import com.wx.server.entity.TbTechAptitude;
import com.wx.server.entity.TbTechAptitudeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTechAptitudeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    int deleteByExample(TbTechAptitudeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    int insert(TbTechAptitude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    int insertSelective(TbTechAptitude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    List<TbTechAptitude> selectByExample(TbTechAptitudeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    TbTechAptitude selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTechAptitude record, @Param("example") TbTechAptitudeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTechAptitude record, @Param("example") TbTechAptitudeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTechAptitude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_aptitude
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTechAptitude record);
}