package com.wx.server.dao;

import com.wx.server.entity.TbTechService;
import com.wx.server.entity.TbTechServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTechServiceMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */
  int deleteByExample(TbTechServiceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */
  int insert(TbTechService record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */
  int insertSelective(TbTechService record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */List<TbTechService> selectByExample(TbTechServiceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */
  TbTechService selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbTechService record,@Param("example") TbTechServiceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */int updateByExample(@Param("record") TbTechService record,@Param("example") TbTechServiceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbTechService record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_tech_service
   * @mbg.generated
   */
  int updateByPrimaryKey(TbTechService record);
}