package com.wx.server.dao;

import com.wx.server.entity.TbTechnicianService;
import com.wx.server.entity.TbTechnicianServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTechnicianServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    int deleteByExample(TbTechnicianServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    int insert(TbTechnicianService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    int insertSelective(TbTechnicianService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    List<TbTechnicianService> selectByExample(TbTechnicianServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    TbTechnicianService selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTechnicianService record, @Param("example") TbTechnicianServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTechnicianService record, @Param("example") TbTechnicianServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTechnicianService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technician_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTechnicianService record);
}