package com.wx.server.dao;

import com.wx.server.entity.TbTechnicianComment;
import com.wx.server.entity.TbTechnicianCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTechnicianCommentMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */
  int deleteByExample(TbTechnicianCommentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */
  int insert(TbTechnicianComment record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */
  int insertSelective(TbTechnicianComment record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */List<TbTechnicianComment> selectByExampleWithBLOBs(TbTechnicianCommentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */List<TbTechnicianComment> selectByExample(TbTechnicianCommentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */
  TbTechnicianComment selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbTechnicianComment record,@Param("example") TbTechnicianCommentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */int updateByExampleWithBLOBs(@Param("record") TbTechnicianComment record,@Param("example") TbTechnicianCommentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */int updateByExample(@Param("record") TbTechnicianComment record,@Param("example") TbTechnicianCommentExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbTechnicianComment record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */
  int updateByPrimaryKeyWithBLOBs(TbTechnicianComment record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_technician_comment
   * @mbg.generated
   */
  int updateByPrimaryKey(TbTechnicianComment record);
}