package com.wx.server.dao;

import com.wx.server.entity.TbTechIdentification;
import com.wx.server.entity.TbTechIdentificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTechIdentificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    int deleteByExample(TbTechIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    int insert(TbTechIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    int insertSelective(TbTechIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    List<TbTechIdentification> selectByExample(TbTechIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    TbTechIdentification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTechIdentification record, @Param("example") TbTechIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTechIdentification record, @Param("example") TbTechIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTechIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tech_identification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTechIdentification record);
}