package com.wx.server.dao;

import com.wx.server.entity.TbTopic;
import com.wx.server.entity.TbTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    long countByExample(TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    int deleteByExample(TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    int insert(TbTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    int insertSelective(TbTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    List<TbTopic> selectByExample(TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    TbTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTopic record, @Param("example") TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTopic record, @Param("example") TbTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTopic record);
}