package com.wx.server.dao;

import com.wx.server.entity.TbUserComment;
import com.wx.server.entity.TbUserCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int deleteByExample(TbUserCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int insert(TbUserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int insertSelective(TbUserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    List<TbUserComment> selectByExampleWithBLOBs(TbUserCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    List<TbUserComment> selectByExample(TbUserCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    TbUserComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbUserComment record, @Param("example") TbUserCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TbUserComment record, @Param("example") TbUserCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbUserComment record, @Param("example") TbUserCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbUserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbUserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbUserComment record);
}