package com.wx.server.entity;

import java.io.Serializable;

public class TbAddress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.addr_user
     *
     * @mbg.generated
     */
    private String addrUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.addr_name
     *
     * @mbg.generated
     */
    private String addrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.addr_tel
     *
     * @mbg.generated
     */
    private String addrTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_address.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_address
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.id
     *
     * @return the value of tb_address.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.id
     *
     * @param id the value for tb_address.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.addr_user
     *
     * @return the value of tb_address.addr_user
     *
     * @mbg.generated
     */
    public String getAddrUser() {
        return addrUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.addr_user
     *
     * @param addrUser the value for tb_address.addr_user
     *
     * @mbg.generated
     */
    public void setAddrUser(String addrUser) {
        this.addrUser = addrUser == null ? null : addrUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.addr_name
     *
     * @return the value of tb_address.addr_name
     *
     * @mbg.generated
     */
    public String getAddrName() {
        return addrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.addr_name
     *
     * @param addrName the value for tb_address.addr_name
     *
     * @mbg.generated
     */
    public void setAddrName(String addrName) {
        this.addrName = addrName == null ? null : addrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.addr_tel
     *
     * @return the value of tb_address.addr_tel
     *
     * @mbg.generated
     */
    public String getAddrTel() {
        return addrTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.addr_tel
     *
     * @param addrTel the value for tb_address.addr_tel
     *
     * @mbg.generated
     */
    public void setAddrTel(String addrTel) {
        this.addrTel = addrTel == null ? null : addrTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.user_id
     *
     * @return the value of tb_address.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.user_id
     *
     * @param userId the value for tb_address.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.sort
     *
     * @return the value of tb_address.sort
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.sort
     *
     * @param sort the value for tb_address.sort
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.city
     *
     * @return the value of tb_address.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.city
     *
     * @param city the value for tb_address.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.province
     *
     * @return the value of tb_address.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.province
     *
     * @param province the value for tb_address.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_address.area
     *
     * @return the value of tb_address.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_address.area
     *
     * @param area the value for tb_address.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }
}