package com.wx.server.entity;

import java.io.Serializable;
import java.util.Date;

public class TbAppointment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.service_id
     *
     * @mbg.generated
     */
    private Integer serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.repair_shop_id
     *
     * @mbg.generated
     */
    private String repairShopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.shop_tel
     *
     * @mbg.generated
     */
    private String shopTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.lat
     *
     * @mbg.generated
     */
    private Double lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.lng
     *
     * @mbg.generated
     */
    private Double lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.status_info
     *
     * @mbg.generated
     */
    private String statusInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_appointment.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_appointment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.id
     *
     * @return the value of tb_appointment.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.id
     *
     * @param id the value for tb_appointment.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.service_id
     *
     * @return the value of tb_appointment.service_id
     *
     * @mbg.generated
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.service_id
     *
     * @param serviceId the value for tb_appointment.service_id
     *
     * @mbg.generated
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.user_id
     *
     * @return the value of tb_appointment.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.user_id
     *
     * @param userId the value for tb_appointment.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.phone
     *
     * @return the value of tb_appointment.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.phone
     *
     * @param phone the value for tb_appointment.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.note
     *
     * @return the value of tb_appointment.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.note
     *
     * @param note the value for tb_appointment.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.amount
     *
     * @return the value of tb_appointment.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.amount
     *
     * @param amount the value for tb_appointment.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.repair_shop_id
     *
     * @return the value of tb_appointment.repair_shop_id
     *
     * @mbg.generated
     */
    public String getRepairShopId() {
        return repairShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.repair_shop_id
     *
     * @param repairShopId the value for tb_appointment.repair_shop_id
     *
     * @mbg.generated
     */
    public void setRepairShopId(String repairShopId) {
        this.repairShopId = repairShopId == null ? null : repairShopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.shop_tel
     *
     * @return the value of tb_appointment.shop_tel
     *
     * @mbg.generated
     */
    public String getShopTel() {
        return shopTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.shop_tel
     *
     * @param shopTel the value for tb_appointment.shop_tel
     *
     * @mbg.generated
     */
    public void setShopTel(String shopTel) {
        this.shopTel = shopTel == null ? null : shopTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.address
     *
     * @return the value of tb_appointment.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.address
     *
     * @param address the value for tb_appointment.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.province
     *
     * @return the value of tb_appointment.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.province
     *
     * @param province the value for tb_appointment.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.city
     *
     * @return the value of tb_appointment.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.city
     *
     * @param city the value for tb_appointment.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.area
     *
     * @return the value of tb_appointment.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.area
     *
     * @param area the value for tb_appointment.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.lat
     *
     * @return the value of tb_appointment.lat
     *
     * @mbg.generated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.lat
     *
     * @param lat the value for tb_appointment.lat
     *
     * @mbg.generated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.lng
     *
     * @return the value of tb_appointment.lng
     *
     * @mbg.generated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.lng
     *
     * @param lng the value for tb_appointment.lng
     *
     * @mbg.generated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.status
     *
     * @return the value of tb_appointment.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.status
     *
     * @param status the value for tb_appointment.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.status_info
     *
     * @return the value of tb_appointment.status_info
     *
     * @mbg.generated
     */
    public String getStatusInfo() {
        return statusInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.status_info
     *
     * @param statusInfo the value for tb_appointment.status_info
     *
     * @mbg.generated
     */
    public void setStatusInfo(String statusInfo) {
        this.statusInfo = statusInfo == null ? null : statusInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.create_time
     *
     * @return the value of tb_appointment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.create_time
     *
     * @param createTime the value for tb_appointment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_appointment.update_time
     *
     * @return the value of tb_appointment.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_appointment.update_time
     *
     * @param updateTime the value for tb_appointment.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}