package com.wx.server.entity;

import java.io.Serializable;

public class TbCarModels implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_models.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_models.first_letter
     *
     * @mbg.generated
     */
    private String firstLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_models.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_models.cars_line
     *
     * @mbg.generated
     */
    private String carsLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_models.valid
     *
     * @mbg.generated
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_car_models
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_models.id
     *
     * @return the value of tb_car_models.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_models.id
     *
     * @param id the value for tb_car_models.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_models.first_letter
     *
     * @return the value of tb_car_models.first_letter
     *
     * @mbg.generated
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_models.first_letter
     *
     * @param firstLetter the value for tb_car_models.first_letter
     *
     * @mbg.generated
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter == null ? null : firstLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_models.brand
     *
     * @return the value of tb_car_models.brand
     *
     * @mbg.generated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_models.brand
     *
     * @param brand the value for tb_car_models.brand
     *
     * @mbg.generated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_models.cars_line
     *
     * @return the value of tb_car_models.cars_line
     *
     * @mbg.generated
     */
    public String getCarsLine() {
        return carsLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_models.cars_line
     *
     * @param carsLine the value for tb_car_models.cars_line
     *
     * @mbg.generated
     */
    public void setCarsLine(String carsLine) {
        this.carsLine = carsLine == null ? null : carsLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_models.valid
     *
     * @return the value of tb_car_models.valid
     *
     * @mbg.generated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_models.valid
     *
     * @param valid the value for tb_car_models.valid
     *
     * @mbg.generated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}