package com.wx.server.entity;

import java.io.Serializable;

public class TbCart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_img
     *
     * @mbg.generated
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_spe
     *
     * @mbg.generated
     */
    private String goodsSpe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_price
     *
     * @mbg.generated
     */
    private Float goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_num
     *
     * @mbg.generated
     */
    private Integer goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.goods_total
     *
     * @mbg.generated
     */
    private Float goodsTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cart.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cart
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.id
     *
     * @return the value of tb_cart.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.id
     *
     * @param id the value for tb_cart.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_id
     *
     * @return the value of tb_cart.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_id
     *
     * @param goodsId the value for tb_cart.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_name
     *
     * @return the value of tb_cart.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_name
     *
     * @param goodsName the value for tb_cart.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_img
     *
     * @return the value of tb_cart.goods_img
     *
     * @mbg.generated
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_img
     *
     * @param goodsImg the value for tb_cart.goods_img
     *
     * @mbg.generated
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_spe
     *
     * @return the value of tb_cart.goods_spe
     *
     * @mbg.generated
     */
    public String getGoodsSpe() {
        return goodsSpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_spe
     *
     * @param goodsSpe the value for tb_cart.goods_spe
     *
     * @mbg.generated
     */
    public void setGoodsSpe(String goodsSpe) {
        this.goodsSpe = goodsSpe == null ? null : goodsSpe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_price
     *
     * @return the value of tb_cart.goods_price
     *
     * @mbg.generated
     */
    public Float getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_price
     *
     * @param goodsPrice the value for tb_cart.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(Float goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_num
     *
     * @return the value of tb_cart.goods_num
     *
     * @mbg.generated
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_num
     *
     * @param goodsNum the value for tb_cart.goods_num
     *
     * @mbg.generated
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.goods_total
     *
     * @return the value of tb_cart.goods_total
     *
     * @mbg.generated
     */
    public Float getGoodsTotal() {
        return goodsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.goods_total
     *
     * @param goodsTotal the value for tb_cart.goods_total
     *
     * @mbg.generated
     */
    public void setGoodsTotal(Float goodsTotal) {
        this.goodsTotal = goodsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cart.user_id
     *
     * @return the value of tb_cart.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cart.user_id
     *
     * @param userId the value for tb_cart.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}