package com.wx.server.entity;

import java.io.Serializable;

public class TbCategory implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_category.id
   * @mbg.generated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_category.pid
   * @mbg.generated
   */
  private Integer pid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_category.ctg_name
   * @mbg.generated
   */
  private String ctgName;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_category.ctg_img
   * @mbg.generated
   */
  private String ctgImg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_category.status
   * @mbg.generated
   */
  private Integer status;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_category.sort
   * @mbg.generated
   */
  private Integer sort;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table tb_category
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_category.id
   * @return  the value of tb_category.id
   * @mbg.generated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_category.id
   * @param id  the value for tb_category.id
   * @mbg.generated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_category.pid
   * @return  the value of tb_category.pid
   * @mbg.generated
   */
  public Integer getPid() {
    return pid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_category.pid
   * @param pid  the value for tb_category.pid
   * @mbg.generated
   */
  public void setPid(Integer pid) {
    this.pid = pid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_category.ctg_name
   * @return  the value of tb_category.ctg_name
   * @mbg.generated
   */
  public String getCtgName() {
    return ctgName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_category.ctg_name
   * @param ctgName  the value for tb_category.ctg_name
   * @mbg.generated
   */
  public void setCtgName(String ctgName) {
    this.ctgName = ctgName == null ? null : ctgName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_category.ctg_img
   * @return  the value of tb_category.ctg_img
   * @mbg.generated
   */
  public String getCtgImg() {
    return ctgImg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_category.ctg_img
   * @param ctgImg  the value for tb_category.ctg_img
   * @mbg.generated
   */
  public void setCtgImg(String ctgImg) {
    this.ctgImg = ctgImg == null ? null : ctgImg.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_category.status
   * @return  the value of tb_category.status
   * @mbg.generated
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_category.status
   * @param status  the value for tb_category.status
   * @mbg.generated
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_category.sort
   * @return  the value of tb_category.sort
   * @mbg.generated
   */
  public Integer getSort() {
    return sort;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_category.sort
   * @param sort  the value for tb_category.sort
   * @mbg.generated
   */
  public void setSort(Integer sort) {
    this.sort = sort;
  }
}