package com.wx.server.entity;

import java.io.Serializable;

public class TbCoupons implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupons.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupons.cps_name
     *
     * @mbg.generated
     */
    private String cpsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupons.cps_code
     *
     * @mbg.generated
     */
    private String cpsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupons.cps_price
     *
     * @mbg.generated
     */
    private Float cpsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupons.cps_time
     *
     * @mbg.generated
     */
    private String cpsTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupons.cps_level
     *
     * @mbg.generated
     */
    private Integer cpsLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupons.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupons.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_coupons
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupons.id
     *
     * @return the value of tb_coupons.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupons.id
     *
     * @param id the value for tb_coupons.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupons.cps_name
     *
     * @return the value of tb_coupons.cps_name
     *
     * @mbg.generated
     */
    public String getCpsName() {
        return cpsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupons.cps_name
     *
     * @param cpsName the value for tb_coupons.cps_name
     *
     * @mbg.generated
     */
    public void setCpsName(String cpsName) {
        this.cpsName = cpsName == null ? null : cpsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupons.cps_code
     *
     * @return the value of tb_coupons.cps_code
     *
     * @mbg.generated
     */
    public String getCpsCode() {
        return cpsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupons.cps_code
     *
     * @param cpsCode the value for tb_coupons.cps_code
     *
     * @mbg.generated
     */
    public void setCpsCode(String cpsCode) {
        this.cpsCode = cpsCode == null ? null : cpsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupons.cps_price
     *
     * @return the value of tb_coupons.cps_price
     *
     * @mbg.generated
     */
    public Float getCpsPrice() {
        return cpsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupons.cps_price
     *
     * @param cpsPrice the value for tb_coupons.cps_price
     *
     * @mbg.generated
     */
    public void setCpsPrice(Float cpsPrice) {
        this.cpsPrice = cpsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupons.cps_time
     *
     * @return the value of tb_coupons.cps_time
     *
     * @mbg.generated
     */
    public String getCpsTime() {
        return cpsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupons.cps_time
     *
     * @param cpsTime the value for tb_coupons.cps_time
     *
     * @mbg.generated
     */
    public void setCpsTime(String cpsTime) {
        this.cpsTime = cpsTime == null ? null : cpsTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupons.cps_level
     *
     * @return the value of tb_coupons.cps_level
     *
     * @mbg.generated
     */
    public Integer getCpsLevel() {
        return cpsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupons.cps_level
     *
     * @param cpsLevel the value for tb_coupons.cps_level
     *
     * @mbg.generated
     */
    public void setCpsLevel(Integer cpsLevel) {
        this.cpsLevel = cpsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupons.user_id
     *
     * @return the value of tb_coupons.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupons.user_id
     *
     * @param userId the value for tb_coupons.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupons.status
     *
     * @return the value of tb_coupons.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupons.status
     *
     * @param status the value for tb_coupons.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}