package com.wx.server.entity;

import java.io.Serializable;

public class TbOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_spe
     *
     * @mbg.generated
     */
    private String goodsSpe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_price
     *
     * @mbg.generated
     */
    private String goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_num
     *
     * @mbg.generated
     */
    private String goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_total
     *
     * @mbg.generated
     */
    private Float goodsTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_total_num
     *
     * @mbg.generated
     */
    private Integer goodsTotalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.addr_name
     *
     * @mbg.generated
     */
    private String addrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.receive
     *
     * @mbg.generated
     */
    private String receive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.cps_id
     *
     * @mbg.generated
     */
    private Integer cpsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.cps_name
     *
     * @mbg.generated
     */
    private String cpsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.cps_price
     *
     * @mbg.generated
     */
    private Float cpsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.add_time
     *
     * @mbg.generated
     */
    private String addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.id
     *
     * @return the value of tb_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.id
     *
     * @param id the value for tb_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_id
     *
     * @return the value of tb_order.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_id
     *
     * @param goodsId the value for tb_order.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_spe
     *
     * @return the value of tb_order.goods_spe
     *
     * @mbg.generated
     */
    public String getGoodsSpe() {
        return goodsSpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_spe
     *
     * @param goodsSpe the value for tb_order.goods_spe
     *
     * @mbg.generated
     */
    public void setGoodsSpe(String goodsSpe) {
        this.goodsSpe = goodsSpe == null ? null : goodsSpe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_price
     *
     * @return the value of tb_order.goods_price
     *
     * @mbg.generated
     */
    public String getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_price
     *
     * @param goodsPrice the value for tb_order.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice == null ? null : goodsPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_num
     *
     * @return the value of tb_order.goods_num
     *
     * @mbg.generated
     */
    public String getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_num
     *
     * @param goodsNum the value for tb_order.goods_num
     *
     * @mbg.generated
     */
    public void setGoodsNum(String goodsNum) {
        this.goodsNum = goodsNum == null ? null : goodsNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_total
     *
     * @return the value of tb_order.goods_total
     *
     * @mbg.generated
     */
    public Float getGoodsTotal() {
        return goodsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_total
     *
     * @param goodsTotal the value for tb_order.goods_total
     *
     * @mbg.generated
     */
    public void setGoodsTotal(Float goodsTotal) {
        this.goodsTotal = goodsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_total_num
     *
     * @return the value of tb_order.goods_total_num
     *
     * @mbg.generated
     */
    public Integer getGoodsTotalNum() {
        return goodsTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_total_num
     *
     * @param goodsTotalNum the value for tb_order.goods_total_num
     *
     * @mbg.generated
     */
    public void setGoodsTotalNum(Integer goodsTotalNum) {
        this.goodsTotalNum = goodsTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.addr_name
     *
     * @return the value of tb_order.addr_name
     *
     * @mbg.generated
     */
    public String getAddrName() {
        return addrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.addr_name
     *
     * @param addrName the value for tb_order.addr_name
     *
     * @mbg.generated
     */
    public void setAddrName(String addrName) {
        this.addrName = addrName == null ? null : addrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.receive
     *
     * @return the value of tb_order.receive
     *
     * @mbg.generated
     */
    public String getReceive() {
        return receive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.receive
     *
     * @param receive the value for tb_order.receive
     *
     * @mbg.generated
     */
    public void setReceive(String receive) {
        this.receive = receive == null ? null : receive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.cps_id
     *
     * @return the value of tb_order.cps_id
     *
     * @mbg.generated
     */
    public Integer getCpsId() {
        return cpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.cps_id
     *
     * @param cpsId the value for tb_order.cps_id
     *
     * @mbg.generated
     */
    public void setCpsId(Integer cpsId) {
        this.cpsId = cpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.cps_name
     *
     * @return the value of tb_order.cps_name
     *
     * @mbg.generated
     */
    public String getCpsName() {
        return cpsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.cps_name
     *
     * @param cpsName the value for tb_order.cps_name
     *
     * @mbg.generated
     */
    public void setCpsName(String cpsName) {
        this.cpsName = cpsName == null ? null : cpsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.cps_price
     *
     * @return the value of tb_order.cps_price
     *
     * @mbg.generated
     */
    public Float getCpsPrice() {
        return cpsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.cps_price
     *
     * @param cpsPrice the value for tb_order.cps_price
     *
     * @mbg.generated
     */
    public void setCpsPrice(Float cpsPrice) {
        this.cpsPrice = cpsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.status
     *
     * @return the value of tb_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.status
     *
     * @param status the value for tb_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.note
     *
     * @return the value of tb_order.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.note
     *
     * @param note the value for tb_order.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.add_time
     *
     * @return the value of tb_order.add_time
     *
     * @mbg.generated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.add_time
     *
     * @param addTime the value for tb_order.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.user_id
     *
     * @return the value of tb_order.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.user_id
     *
     * @param userId the value for tb_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}