package com.wx.server.entity;

import java.io.Serializable;
import java.util.Date;

public class TbReply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reply.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reply.topic_id
     *
     * @mbg.generated
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reply.reply_text
     *
     * @mbg.generated
     */
    private String replyText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reply.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reply.favor_count
     *
     * @mbg.generated
     */
    private Integer favorCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reply.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reply.valid
     *
     * @mbg.generated
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_reply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reply.id
     *
     * @return the value of tb_reply.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reply.id
     *
     * @param id the value for tb_reply.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reply.topic_id
     *
     * @return the value of tb_reply.topic_id
     *
     * @mbg.generated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reply.topic_id
     *
     * @param topicId the value for tb_reply.topic_id
     *
     * @mbg.generated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reply.reply_text
     *
     * @return the value of tb_reply.reply_text
     *
     * @mbg.generated
     */
    public String getReplyText() {
        return replyText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reply.reply_text
     *
     * @param replyText the value for tb_reply.reply_text
     *
     * @mbg.generated
     */
    public void setReplyText(String replyText) {
        this.replyText = replyText == null ? null : replyText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reply.create_time
     *
     * @return the value of tb_reply.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reply.create_time
     *
     * @param createTime the value for tb_reply.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reply.favor_count
     *
     * @return the value of tb_reply.favor_count
     *
     * @mbg.generated
     */
    public Integer getFavorCount() {
        return favorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reply.favor_count
     *
     * @param favorCount the value for tb_reply.favor_count
     *
     * @mbg.generated
     */
    public void setFavorCount(Integer favorCount) {
        this.favorCount = favorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reply.user_id
     *
     * @return the value of tb_reply.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reply.user_id
     *
     * @param userId the value for tb_reply.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reply.valid
     *
     * @return the value of tb_reply.valid
     *
     * @mbg.generated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reply.valid
     *
     * @param valid the value for tb_reply.valid
     *
     * @mbg.generated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}