package com.wx.server.entity;

import java.io.Serializable;

public class TbService implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_service.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_service.caretory_id
     *
     * @mbg.generated
     */
    private Integer caretoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_service.service_name
     *
     * @mbg.generated
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_service.service_desc
     *
     * @mbg.generated
     */
    private String serviceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_service.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_service.commision
     *
     * @mbg.generated
     */
    private Double commision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_service.benefit_price
     *
     * @mbg.generated
     */
    private Double benefitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_service.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_service
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_service.id
     *
     * @return the value of tb_service.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_service.id
     *
     * @param id the value for tb_service.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_service.caretory_id
     *
     * @return the value of tb_service.caretory_id
     *
     * @mbg.generated
     */
    public Integer getCaretoryId() {
        return caretoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_service.caretory_id
     *
     * @param caretoryId the value for tb_service.caretory_id
     *
     * @mbg.generated
     */
    public void setCaretoryId(Integer caretoryId) {
        this.caretoryId = caretoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_service.service_name
     *
     * @return the value of tb_service.service_name
     *
     * @mbg.generated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_service.service_name
     *
     * @param serviceName the value for tb_service.service_name
     *
     * @mbg.generated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_service.service_desc
     *
     * @return the value of tb_service.service_desc
     *
     * @mbg.generated
     */
    public String getServiceDesc() {
        return serviceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_service.service_desc
     *
     * @param serviceDesc the value for tb_service.service_desc
     *
     * @mbg.generated
     */
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc == null ? null : serviceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_service.price
     *
     * @return the value of tb_service.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_service.price
     *
     * @param price the value for tb_service.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_service.commision
     *
     * @return the value of tb_service.commision
     *
     * @mbg.generated
     */
    public Double getCommision() {
        return commision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_service.commision
     *
     * @param commision the value for tb_service.commision
     *
     * @mbg.generated
     */
    public void setCommision(Double commision) {
        this.commision = commision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_service.benefit_price
     *
     * @return the value of tb_service.benefit_price
     *
     * @mbg.generated
     */
    public Double getBenefitPrice() {
        return benefitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_service.benefit_price
     *
     * @param benefitPrice the value for tb_service.benefit_price
     *
     * @mbg.generated
     */
    public void setBenefitPrice(Double benefitPrice) {
        this.benefitPrice = benefitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_service.sort
     *
     * @return the value of tb_service.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_service.sort
     *
     * @param sort the value for tb_service.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}