package com.wx.server.entity;

import java.io.Serializable;

public class TbTechnician implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_technician.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_technician.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_technician.realname
     *
     * @mbg.generated
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_technician.seniority
     *
     * @mbg.generated
     */
    private Integer seniority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_technician.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_technician.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_technician.order_month
     *
     * @mbg.generated
     */
    private Integer orderMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_technician.score
     *
     * @mbg.generated
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_technician
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_technician.id
     *
     * @return the value of tb_technician.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_technician.id
     *
     * @param id the value for tb_technician.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_technician.user_id
     *
     * @return the value of tb_technician.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_technician.user_id
     *
     * @param userId the value for tb_technician.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_technician.realname
     *
     * @return the value of tb_technician.realname
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_technician.realname
     *
     * @param realname the value for tb_technician.realname
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_technician.seniority
     *
     * @return the value of tb_technician.seniority
     *
     * @mbg.generated
     */
    public Integer getSeniority() {
        return seniority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_technician.seniority
     *
     * @param seniority the value for tb_technician.seniority
     *
     * @mbg.generated
     */
    public void setSeniority(Integer seniority) {
        this.seniority = seniority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_technician.phone
     *
     * @return the value of tb_technician.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_technician.phone
     *
     * @param phone the value for tb_technician.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_technician.description
     *
     * @return the value of tb_technician.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_technician.description
     *
     * @param description the value for tb_technician.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_technician.order_month
     *
     * @return the value of tb_technician.order_month
     *
     * @mbg.generated
     */
    public Integer getOrderMonth() {
        return orderMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_technician.order_month
     *
     * @param orderMonth the value for tb_technician.order_month
     *
     * @mbg.generated
     */
    public void setOrderMonth(Integer orderMonth) {
        this.orderMonth = orderMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_technician.score
     *
     * @return the value of tb_technician.score
     *
     * @mbg.generated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_technician.score
     *
     * @param score the value for tb_technician.score
     *
     * @mbg.generated
     */
    public void setScore(Double score) {
        this.score = score;
    }
}